from __future__ import annotations

import json
import random
from dataclasses import dataclass
from itertools import chain
from pathlib import Path
from typing import Dict, Iterable, Optional

import numpy as np
import torch
from torch_geometric.data import Data
from torch_geometric.datasets import Amazon, Coauthor, Planetoid
from torch_geometric.transforms import NormalizeFeatures
from torch_geometric.utils import coalesce, remove_self_loops, to_undirected

try:
    from ogb.nodeproppred import PygNodePropPredDataset
except Exception:
    PygNodePropPredDataset = None


ALIASES = {
    'cora': 'cora',
    'pubmed': 'pubmed',
    'computers': 'amazon_computers',
    'amazon_computers': 'amazon_computers',
    'amazon-computers': 'amazon_computers',
    'photo': 'amazon_photo',
    'amazon_photo': 'amazon_photo',
    'amazon-photo': 'amazon_photo',
    'cs': 'coauthor_cs',
    'coauthor_cs': 'coauthor_cs',
    'coauthor-cs': 'coauthor_cs',
    'physics': 'coauthor_physics',
    'coauthor_physics': 'coauthor_physics',
    'coauthor-physics': 'coauthor_physics',
    'wiki': 'wiki_cs',
    'wikics': 'wiki_cs',
    'wiki_cs': 'wiki_cs',
    'wiki-cs': 'wiki_cs',
    'arxiv': 'ogbn_arxiv',
    'ogbn-arxiv': 'ogbn_arxiv',
    'ogbn_arxiv': 'ogbn_arxiv',
}

DATASETS = [
    'cora',
    'pubmed',
    'amazon_computers',
    'amazon_photo',
    'coauthor_cs',
    'coauthor_physics',
    'wiki_cs',
    'ogbn_arxiv',
]


@dataclass
class GraphBundle:
    name: str
    data: object
    num_classes: int


def canonical_name(name: str) -> str:
    key = name.lower().strip().replace(' ', '_')
    if key not in ALIASES:
        raise ValueError(f'Unsupported dataset {name}. Supported: {DATASETS}')
    return ALIASES[key]


def _row_normalize_x(x: torch.Tensor) -> torch.Tensor:
    """Match the row-wise feature normalization used by the original ODINN code."""
    x = x.float()
    denom = x.sum(dim=1, keepdim=True)
    denom = torch.where(denom.abs() < 1e-12, torch.ones_like(denom), denom)
    return x / denom


def _first_existing(candidates: Iterable[Path]) -> Optional[Path]:
    for p in candidates:
        if p.exists():
            return p
    return None


def _require_local(path: Optional[Path], dataset: str, expected: str) -> Path:
    if path is None:
        raise FileNotFoundError(
            f'Local files for {dataset} were not found. Expected one of: {expected}. '
            'This reproduction loader does not silently download datasets.'
        )
    return path


def _load_local_wikics(json_path: Path) -> Data:
    """Load wiki-cs/dataset/data.json using the same structure as PyG WikiCS.

    The old ODINN project also reads this exact JSON file directly. We do not use
    WikiCS(root=...) here because the user's local file layout is
    ``wiki-cs/dataset/data.json`` rather than PyG's ``root/raw/data.json`` layout.
    """
    with json_path.open('r', encoding='utf-8') as f:
        obj = json.load(f)

    x = torch.tensor(obj['features'], dtype=torch.float)
    y = torch.tensor(obj['labels'], dtype=torch.long)

    edges = [[(i, j) for j in js] for i, js in enumerate(obj['links'])]
    edges = list(chain(*edges))
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    edge_index = to_undirected(edge_index, num_nodes=x.size(0))

    # The paper uses our own random 1/3/5-shot splits, so the official Wiki-CS
    # train/val/test masks are intentionally not used here.
    return Data(x=_row_normalize_x(x), y=y, edge_index=edge_index)


def load_dataset(name: str, root: str = 'data') -> GraphBundle:
    """Load one of the eight WSDM datasets from the user's existing local layout.

    Expected local layout (relative to the project root):

      data/pyg/planetoid/Cora or cora
      data/pyg/planetoid/PubMed or pubmed
      data/pyg/Computers
      data/pyg/Photo
      data/pyg/CS
      data/pyg/Physics
      wiki-cs/dataset/data.json
      data/ogb/ogbn_arxiv

    No official dataset split is used for the few-shot experiments. Splits are
    generated by ``fewshot_split`` below for every seed.
    """
    name = canonical_name(name)
    root_path = Path(root).expanduser().resolve()
    project_root = root_path.parent
    transform = NormalizeFeatures()

    if name == 'cora':
        planetoid_root = root_path / 'pyg' / 'planetoid'
        folder = _require_local(
            _first_existing([planetoid_root / 'Cora', planetoid_root / 'cora']),
            'cora',
            f'{planetoid_root}/Cora or {planetoid_root}/cora',
        )
        # Planetoid uses root/name/{raw,processed}. Passing the directory name
        # exactly prevents a case-mismatch from triggering a download.
        ds = Planetoid(root=str(planetoid_root), name=folder.name, transform=transform)
        data = ds[0]

    elif name == 'pubmed':
        planetoid_root = root_path / 'pyg' / 'planetoid'
        folder = _require_local(
            _first_existing([planetoid_root / 'PubMed', planetoid_root / 'pubmed']),
            'pubmed',
            f'{planetoid_root}/PubMed or {planetoid_root}/pubmed',
        )
        ds = Planetoid(root=str(planetoid_root), name=folder.name, transform=transform)
        data = ds[0]

    elif name == 'amazon_computers':
        # Your files are data/pyg/Computers/{raw,processed}; therefore the PyG
        # root must be data/pyg (not data/pyg/amazon).
        pyg_root = root_path / 'pyg'
        _require_local(
            _first_existing([pyg_root / 'Computers']),
            'amazon_computers',
            f'{pyg_root}/Computers',
        )
        ds = Amazon(root=str(pyg_root), name='Computers', transform=transform)
        data = ds[0]

    elif name == 'amazon_photo':
        pyg_root = root_path / 'pyg'
        _require_local(
            _first_existing([pyg_root / 'Photo']),
            'amazon_photo',
            f'{pyg_root}/Photo',
        )
        ds = Amazon(root=str(pyg_root), name='Photo', transform=transform)
        data = ds[0]

    elif name == 'coauthor_cs':
        # Your files are data/pyg/CS/{raw,processed}; therefore the PyG root is
        # data/pyg (not data/pyg/coauthor).
        pyg_root = root_path / 'pyg'
        folder = _require_local(
            _first_existing([pyg_root / 'CS', pyg_root / 'cs']),
            'coauthor_cs',
            f'{pyg_root}/CS or {pyg_root}/cs',
        )
        ds = Coauthor(root=str(pyg_root), name=folder.name, transform=transform)
        data = ds[0]

    elif name == 'coauthor_physics':
        pyg_root = root_path / 'pyg'
        folder = _require_local(
            _first_existing([pyg_root / 'Physics', pyg_root / 'physics']),
            'coauthor_physics',
            f'{pyg_root}/Physics or {pyg_root}/physics',
        )
        ds = Coauthor(root=str(pyg_root), name=folder.name, transform=transform)
        data = ds[0]

    elif name == 'wiki_cs':
        wiki_json = _require_local(
            _first_existing([
                project_root / 'wiki-cs' / 'dataset' / 'data.json',
                root_path / 'wiki-cs' / 'dataset' / 'data.json',
                Path.cwd() / 'wiki-cs' / 'dataset' / 'data.json',
            ]),
            'wiki_cs',
            'wiki-cs/dataset/data.json',
        )
        data = _load_local_wikics(wiki_json)

    elif name == 'ogbn_arxiv':
        if PygNodePropPredDataset is None:
            raise ImportError('ogb is required for ogbn-arxiv: pip install ogb')

        # Standard OGB layout:
        #   root=data/ogb -> data/ogb/ogbn_arxiv/{raw,processed,split,...}
        # Your server already contains this path, so no download is needed.
        std_ogb_root = root_path / 'ogb'
        nested_ogb_root = root_path / 'ogb' / 'ogbn-arxiv'
        if (std_ogb_root / 'ogbn_arxiv').exists():
            ogb_root = std_ogb_root
        elif (nested_ogb_root / 'ogbn_arxiv').exists():
            ogb_root = nested_ogb_root
        else:
            raise FileNotFoundError(
                'Local ogbn-arxiv was not found. Expected '
                f'{std_ogb_root / "ogbn_arxiv"} or '
                f'{nested_ogb_root / "ogbn_arxiv"}.'
            )

        # IMPORTANT: Keep the original OGB edge orientation (1,166,243 edges),
        # matching the WSDM table. We do NOT call ToUndirected for ogbn-arxiv.
        ds = PygNodePropPredDataset(
            name='ogbn-arxiv',
            root=str(ogb_root),
            transform=transform,
        )
        data = ds[0]

    else:
        raise AssertionError(name)

    data.y = data.y.view(-1).long()

    if name != 'ogbn_arxiv':
        # This matches the old project's graph handling. In particular, Wiki-CS
        # is symmetrized and then self-loops are removed, reproducing the paper's
        # 215,863-edge statistic from the local JSON.
        data.edge_index = to_undirected(data.edge_index, num_nodes=data.num_nodes)

    data.edge_index, _ = remove_self_loops(data.edge_index)
    data.edge_index = coalesce(data.edge_index, num_nodes=data.num_nodes)

    num_classes = int(data.y.max().item()) + 1
    return GraphBundle(name=name, data=data, num_classes=num_classes)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def fewshot_split(
    y: torch.Tensor,
    shots: int,
    seed: int,
    val_fraction_of_remaining: float = 0.1,
) -> Dict[str, torch.Tensor]:
    """Randomly sample exactly ``shots`` labeled nodes per class.

    This is also the intended ogbn-arxiv protocol: for #LN=1/3/5, sample
    exactly 1/3/5 nodes from EACH of its 40 classes for training, then randomly
    split all remaining nodes into validation:test = 1:9. The official OGB
    time split under ``split/time`` is deliberately NOT used in these few-shot
    experiments. Repeating seeds 42..71 gives the required 30 random splits.
    """
    if shots <= 0:
        raise ValueError('shots must be positive')
    if not (0.0 < val_fraction_of_remaining < 1.0):
        raise ValueError('val_fraction_of_remaining must lie in (0, 1)')

    y_cpu = y.detach().cpu().view(-1)
    num_classes = int(y_cpu.max().item()) + 1
    g = torch.Generator().manual_seed(seed)

    train_parts = []
    chosen = torch.zeros(y_cpu.numel(), dtype=torch.bool)

    for c in range(num_classes):
        idx = (y_cpu == c).nonzero(as_tuple=False).view(-1)
        if idx.numel() < shots:
            raise ValueError(
                f'Class {c} contains only {idx.numel()} nodes, fewer than shots={shots}.'
            )
        perm = idx[torch.randperm(idx.numel(), generator=g)]
        sel = perm[:shots]
        chosen[sel] = True
        train_parts.append(sel)

    train_idx = torch.cat(train_parts)

    remain = (~chosen).nonzero(as_tuple=False).view(-1)
    remain = remain[torch.randperm(remain.numel(), generator=g)]

    # Match the old project/paper setting: remaining nodes are split 1:9.
    n_val = int(remain.numel() * val_fraction_of_remaining)
    if remain.numel() > 1:
        n_val = max(1, min(n_val, remain.numel() - 1))
    else:
        n_val = remain.numel()

    val_idx = remain[:n_val]
    test_idx = remain[n_val:]

    def mask(idx: torch.Tensor) -> torch.Tensor:
        out = torch.zeros(y_cpu.numel(), dtype=torch.bool)
        out[idx] = True
        return out

    return {
        'train': mask(train_idx),
        'val': mask(val_idx),
        'test': mask(test_idx),
    }
